alias l="ls -lh" \
      c=clear \
      python=python3 \
      py=python3 \
      pip=pip3 \
      cl="c && l" \
      g=git \
      gst="git status" \
      d-c=docker-compose \
      _brightness="xrandr --output eDP-1-1 --brightness" \
      _suspend="systemctl suspend" \
      vim=nvim
