#!/bin/bash

OLD_PWD=$PWD

sudo apt-get update -yq && \
sudo apt-get upgrade -yq && \
sudo apt-get install curl tree nitrogen -yq && \
sudo apt-get autoremove -yq

# Python
sudo apt install python3 python3-pip -yq && \
pip3 install -q virtualenv

# Vim
sudo apt install vim -yq && \
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim && \
mkdir ~/.vim/undodir/ -p && \
vim -c PlugInstall -c 'qa!' && \
cd ~/.vim/plugged/YouCompleteMe && \
python3 install.py --all && \
cd -

# Docker
# Taken from: https://docs.docker.com/engine/install/ubuntu/
sudo apt-get remove -y docker docker-engine docker.io containerd runc
sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common && \
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
sudo add-apt-repository -y \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable" && \
sudo apt-get update -y && \
sudo apt-get install -y docker-ce docker-ce-cli containerd.io && \
sudo usermod -aG docker $USER

# Docker-compose
sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
sudo chmod +x /usr/local/bin/docker-compose

# CUDA and NVIDIA container toolkit
sudo apt install -y nvidia-cuda-toolkit
# Taken from: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#install-guide
distribution=$(. /etc/os-release;echo $ID$VERSION_ID) && \
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - && \
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list && \
sudo apt-get update && \
sudo apt-get install -y nvidia-docker2 && \
sudo systemctl restart docker

# Desktop applications
sudo apt-get install -y blueman i3 htop brave

# Brave
curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add - && \
echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list && \
sudo apt update -yq && sudo apt install -yq brave-browser

cd $OLD_PWD
