#!/bin/bash

# Add dotfiles
dotfiles=".vimrc .profile .gitconfig .bashrc .bash_aliases .Xresources .xinitrc"
for dotfile in $dotfiles
do
	echo "Creating symlink for $PWD/$dotfile in $HOME/$dotfile"
	ln -f -s $PWD/$dotfile $HOME/$dotfile
done

config_dirs="i3 i3status"
for cfg in $config_dirs
do
	echo "Creating symlink for $PWD/$cfg in $HOME/.config/$cfg"
	ln -f -s $PWD/$cfg $HOME/.config
done
