#!/bin/bash

# Add dotfiles
dotfiles=".vimrc .profile .gitconfig .bashrc .bash_aliases .Xresources .xinitrc .tmux.conf"
for dotfile in $dotfiles
do
	echo "Creating symlink for $PWD/$dotfile in $HOME/$dotfile"
	ln -f -s $PWD/$dotfile $HOME/$dotfile
done

mkdir $HOME/.config/nvim/
ln -f -s $PWD/.vimrc $HOME/.config/nvim/init.vim

config_dirs="i3 i3status"
for cfg in $config_dirs
do
	echo "Creating symlink for $PWD/$cfg in $HOME/.config/$cfg"
	ln -f -s $PWD/$cfg $HOME/.config
done
