#!/bin/bash

sudo apt-get update -yq && \
sudo apt-get upgrade -yq && \
sudo apt install vim python3 python3-pip -yq && \
sudo apt-get autoremove -yq

# Add dotfiles
dotfiles=".vimrc .profile .gitconfig .bashrc"
for dotfile in $dotfiles
do
	echo "Creating symlink for $PWD/$dotfile in $HOME/$dotfile"
	ln -s $PWD/$dotfile $HOME/$dotfile
done

source ~/.profile
vim -c PlugInstall -c 'qa!'

source ./programs
