#!/bin/bash

source ./programs

# Add dotfiles
dotfiles=".vimrc .profile .gitconfig .bashrc .bash_aliases"
for dotfile in $dotfiles
do
	echo "Creating symlink for $PWD/$dotfile in $HOME/$dotfile"
	ln -s $PWD/$dotfile $HOME/$dotfile
done

source ~/.profile

